addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.11")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"          % "5.6.0")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.11.0")
